export const NAME = 'market-mobile/leads';

export const LINK_OPPORTUNITY_TO_LEAD_FAILURE_NAME =
  'leads/LINK_OPPORTUNITY_TO_LEAD_FAILURE_NAME';

export const CREATE_OPPORTUNITY_FROM_LEAD_FAILURE_NAME =
  'leads/CREATE_OPPORTUNITY_FROM_LEAD_FAILURE_NAME';
